// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXazntF6Mhe--_i-9yCIGeu0wDVei_9xY',
    appId: '1:1085752375628:android:9a85e7728c2d43c376b7e9',
    messagingSenderId: '1085752375628',
    projectId: 'aquaculture-6604c',
    storageBucket: 'aquaculture-6604c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJblGtkJ5-XebMxEdFsawvd6p6o8hgQo',
    appId: '1:1085752375628:ios:eed71e9b54fd37d876b7e9',
    messagingSenderId: '1085752375628',
    projectId: 'aquaculture-6604c',
    storageBucket: 'aquaculture-6604c.firebasestorage.app',
    androidClientId: '1085752375628-58luob7jg4suk8hv355re0j6p7frnndo.apps.googleusercontent.com',
    iosClientId: '1085752375628-99qu2odkrc7t7nebu6gv7mq3ptearpa1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaculture',
  );

}